### ISSUE TITLE
Can't specify any class based args from the command line

### ISSUE THREAD

**Issue by tannerburson** [Tapjoy/chore#5]
If you attempt to specify any of the class based args (consumer, publisher, strategies, etc), you can only use classes that exist inside of Chore. Because Chore doesn't attempt to call `Bundler.setup` or `.require` the only classes loaded are Chore itself. 

This makes it difficult to configure an app that is using a different queue implementation, without making the application itself aware of the change.

ping @StabbyCutyou

**Comment by StabbyCutyou** [comment]
I'm guessing this is strictly the cmd line args, and not in something like a chore.rb?

**Comment by StabbyCutyou** [comment]
In hindsight, the answer to my question was obvious.

I have a fix for this (I tested it with your disque consumer, it's able to load the constant at run time but then you have some downstream bugs that break things - however the CLI parsing is able to do it's thing).

I'd ping you on the actual PR to fix this but you recall the release process that we still use for this project. Once someone LGTMs it, i'll cut the gem for you and push it to rubygems.

**Comment by tannerburson** [comment]
Thanks! I'll keep my eye out for the version bump.

**Comment by tannerburson** [comment]
Fixed in the 1.7 release.
